Jenkinsfile, README.md
- [FIT-628](https://osi-cwds.atlassian.net/browse/FIT-628)
Adds a pull request build for snapshot
=> Setting up PR Build

docker-compose.yml
No story
Ferb, Dora, and perry pointing to integration since PreInt is decommissioned. 
change docker-compose.yml.
No test needed
=> Update dev environment to point to integration by default

app/assets/stylesheets/shame_overrides.scss
- [Alignment issue in IE](https://osi-cwds.atlassian.net/browse/CMO-95)
Fixed alignment issue in IE. 
Before:
After:
CSS change no test needed
=> Fixed remove alignment in IE

app/javascript/snapshots/SnapshotDetailPage.jsx, app/javascript/snapshots/SnapshotSideBar.jsx, app/javascript/views/SideBarPeople.jsx, spec/javascripts/components/SnapshotDetailPageSpec.jsx, spec/javascripts/components/snapshots/SnapshotSideBarSpec.jsx, spec/javascripts/views/SideBarPeopleSpec.jsx
- [Added Left Nav](https://osi-cwds.atlassian.net/browse/CMO-96)
Added Left Nav.
Before:
After:
=> CMO-96 Added Left Nav in Snapshot Details page

app/javascript/snapshots/SnapshotDetailPage.jsx, app/javascript/snapshots/SnapshotSideBar.jsx, spec/javascripts/components/SnapshotDetailPageSpec.jsx, spec/javascripts/components/snapshots/SnapshotSideBarSpec.jsx
No story
Fix the cut off issue between name and card. 
Before:
After:
=> CMO-96 Fixed cut off issue between name and card

app/assets/stylesheets/navigation.scss
No story
Fix scroll bar position issue. Please see screenshot for more detail. 
Before:
After:
CSS change, no test needed
=> CMO-96 Fix scroll bar position issue

app/assets/stylesheets/navigation.scss
- [Fixed scroll bar issue in IE](https://osi-cwds.atlassian.net/browse/CMO-96)
Fixed scroll bar issue in IE
Note: Since IE and Edge do not support `width: max-content` property. I used this alternative.
Before:
After:
css change no test needed
=> Fixed IE issue

spec/javascripts/components/common/RelationshipsSpec.jsx
No Story
There was a missing karma test after the merge. Adding it back in so that we have good coverage;.
=> Add the relationship test back in and make it test what it should

Jenkinsfile
- [Name of Story INT-NNN](https://osi-cwds.atlassian.net/browse/INT-NNN)
=> Master build for snapshot

scripts/ci/acceptance_test.rb
- No Story
This fixes the master build to correctly use integrated test environment to run acceptance tests. Not an ideal way of fixing this but it should work.
=> Fix acceptance testing to use integrated test environment correctly

app/javascript/common/HyphenatedMaskedInput.jsx, app/javascript/common/MaskedInputField.jsx, app/javascript/utils/moveCursor.js, spec/javascripts/components/common/HyphenatedMaskedInputSpec.jsx, spec/javascripts/components/common/MaskedInputFieldSpec.jsx
- [SSN & Client ID Field Constraints](https://osi-cwds.atlassian.net/browse/CMO-175)
1. Users will be able to make single, partial or complete changes in any of the data fields for SSN and Client ID starting from any place they put their cursor on.  
2. Users will be able to highlight any number or numbers and make changes in the highlighted areas in the SSN or Client ID fields 
Note: For more details check JIRA comment.
=> CMO-175 Made masked input field user friendly

README.md
=> Test master build trigger

README.md
=> Revert "Test master build trigger"

app/javascript/views/people/PhoneNumbersShow.jsx, spec/javascripts/views/people/PhoneNumbersShowSpec.jsx
- [Phone number hyperlink issue in Edge](https://osi-cwds.atlassian.net/browse/CMO-176)
Fix phone number hyperlink issue in Edge.
=> CMO-176 Fix phone number hyperlink issue in Edge

scripts/ci/clean.rb
No Story
The clean step is not working because of some previous changes. This should fix that problem.
=> Fix master build clean script to point to the right compose file

app/javascript/views/people/PhoneNumbersShow.jsx, spec/javascripts/views/people/PhoneNumbersShowSpec.jsx
- [Fix phone numbers padding](https://osi-cwds.atlassian.net/browse/CMO-176)
Fix padding for phone number.
=> Fixed paddding for phone numbers

scripts/ci/clean.rb
- No Story
The clean stage is not working in the master build part of the pipeline. adding some print statements to debug this. There will be follow up efforts once the problem is determined.
=> Add some print statements to debug clean stage in pipeline

scripts/ci/clean.rb
- No Story
The clean stage is not working in the master build part of the pipeline. Correcting the project name in the hopes that this will fix the clean step and correctly bring down the bubble.
=> Update the bubble arguments to use the correct project name

app/javascript/sagas/fetchPeopleSearchSaga.js, app/javascript/selectors/userInfoSelectors.js, spec/javascripts/sagas/fetchPeopleSearchSagaSpec.js, spec/javascripts/selectors/userInfoSelectorsSpec.js
- [Search By County New Relic metrics ](https://osi-cwds.atlassian.net/browse/CMO-194)
Added search by county metrics.
=> CMO-194 New relic metrics for search by county

app/javascript/sagas/fetchPeopleSearchSaga.js, spec/javascripts/sagas/fetchPeopleSearchSagaSpec.js
No story
Changed `county` to `staff_county` to be consistent with how CANS tracks county staff.
=> Change county to staff_county

app/javascript/common/search/Autocompleter.jsx, spec/javascripts/components/common/search/AutocompleterSpec.jsx
- [Disable search button upon deletion of data in search fields](https://osi-cwds.atlassian.net/browse/CMO-150)
Fixed the disable/enable search button issue for the DOB field.
Before:
After:
=> CMO-150 Fixed disable/enable search button issue

app/javascript/common/Relationships.jsx, app/javascript/common/relationship/AttachLink.jsx, app/javascript/containers/snapshot/RelationshipsContainer.js, spec/javascripts/components/common/RelationshipsSpec.jsx, spec/javascripts/components/common/relationship/AttachLinkSpec.jsx
- [Log number of attaches by county](https://osi-cwds.atlassian.net/browse/CMO-240)
Log number of attaches by county
=> CMO-240 New Relic Log number of attaches by county

app/javascript/common/search/SearchResultsTable.jsx, spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
- [Log search result click](https://osi-cwds.atlassian.net/browse/CMO-247)
Log search result click to New Relic
=> CMO-247 Log searchResultClick

app/javascript/common/search/PersonSearchResults.jsx, app/javascript/common/search/SearchResultsTable.jsx, app/javascript/containers/snapshot/PersonSearchResultsContainer.js, spec/javascripts/components/common/search/PersonSearchResultsSpec.jsx, spec/javascripts/components/common/search/SearchResultsTableSpec.jsx
- [Log staffId and county_staff along with searchResultClick](https://osi-cwds.atlassian.net/browse/CMO-247)
Log staffId and county_staff along with searchResultClick
=> CMO-247 logged staffId and staff_county

app/javascript/utils/peopleSearchHelper.js
- [Correct Kafka Elastisearch values found in CMO-264 (CMO-280)](https://osi-cwds.atlassian.net/browse/CMO-280)
No functionality was changed
=> Fix some elastic search null value issues

app/javascript/common/search/Autocompleter.jsx, app/javascript/common/search/PersonSearchButtonGroup.jsx, app/javascript/views/AdvancedSearchForm.jsx, app/javascript/views/advancedSearch/AdvancedSearchValidationSchema.jsx, app/javascript/views/advancedSearch/AgeField.jsx, app/javascript/views/advancedSearch/ApproximateAgeField.jsx, app/javascript/views/advancedSearch/ApproximateAgeSelect.jsx, app/javascript/views/advancedSearch/DateOfBirthField.jsx, app/javascript/views/advancedSearch/NameFields.jsx, app/javascript/views/advancedSearch/SexAtBirthAndCountyFields.jsx, app/javascript/views/advancedSearch/formikWrappers/SearchByAgeWrapper.jsx, app/javascript/views/people/PersonSearchForm.jsx, package.json, spec/javascripts/views/AdvancedSearchFormSpec.jsx, spec/javascripts/views/advancedSearch/AgeFieldSpec.jsx, spec/javascripts/views/advancedSearch/ApproximateAgeFieldSpec.jsx, spec/javascripts/views/advancedSearch/ApproximateAgeSelectSpec.jsx, spec/javascripts/views/advancedSearch/DateOfBirthFieldSpec.jsx, spec/javascripts/views/advancedSearch/NameFieldsSpec.jsx, spec/javascripts/views/advancedSearch/SexAtBirthAndCountyFieldsSpec.jsx, spec/javascripts/views/advancedSearch/formikWrappers/SearchByAgeWrapperSpec.jsx, yarn.lock
- [DOB Validation Error is needed CMO-152](https://osi-cwds.atlassian.net/browse/CMO-152)
This does a large refactor to replace the snapshot search form with formik.
There is a lot of code that can be removed. I don't have time to remove it before I leave.
=> CMO-152 DOB Validation Error Formik Version
